### ISSUE TITLE
App crashes on recieving device after receiving .zip file

### ISSUE THREAD

**Issue by colinkiama** [stevenmcountryman/Share-Across-Devices#1]
In case it has something to do with the file size, the zip files that I've tried to send over are around 16 MB or higher. I haven't tested it with zip files with small sizes yet.

**Comment by 2ab15472** [comment]
Hello, I LOVE this application that I recommended to family members. Unfortunately, I have the same issue as my brother which is than I can send from SP4 (Fall Creative Update) to L950 but not an image from L950 to SP4.
Same issue with my brother (SP3, L650).
I have an "Open connection..." message and after a few second, a message telling me "Something is blocking me :("
It works just fine for text and links but not for image on the phone...
